"""A deterministic fixture model repository.

Built rather than committed: boundary fixtures generated by code in CI never fossilise
(constitution, "the boundary fixtures"). Author, committer and dates are fixed, so the same
content produces the same commit sha on every machine — which is what makes a committed golden
digest, and therefore the cross-architecture determinism check, mean anything at all.

Two co-flagships: Netflix retrospective (a resolved outcome to score against) and Intel live
(a forecast with no answer key yet). Both at toy depth — this is a fixture, not a model.
"""

from __future__ import annotations

import os
import subprocess
from pathlib import Path

# Empty-blob digest: a substrate reference that deliberately resolves to nothing, so the
# reference form is exercised with no substrate present.
ABSENT_SUBSTRATE = "sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855:0"

_FIXED_DATE = "2026-01-01T00:00:00+00:00"
_GIT_ENV = {
    "GIT_AUTHOR_NAME": "twin fixture",
    "GIT_AUTHOR_EMAIL": "fixture@twin.invalid",
    "GIT_COMMITTER_NAME": "twin fixture",
    "GIT_COMMITTER_EMAIL": "fixture@twin.invalid",
    "GIT_AUTHOR_DATE": _FIXED_DATE,
    "GIT_COMMITTER_DATE": _FIXED_DATE,
    "GIT_CONFIG_NOSYSTEM": "1",
    "HOME": "/nonexistent-twin-fixture-home",
    "XDG_CONFIG_HOME": "/nonexistent-twin-fixture-home",
    "LC_ALL": "C",
    "TZ": "UTC",
    "PATH": os.environ.get("PATH", "/usr/bin:/bin"),
}
# Anything that could change the bytes git writes or the commit header it builds.
_CONFIG = [
    "-c", "core.autocrlf=false",
    "-c", "core.symlinks=false",
    "-c", "commit.gpgsign=false",
    "-c", "tag.gpgsign=false",
    "-c", "user.name=twin fixture",
    "-c", "user.email=fixture@twin.invalid",
]

WORLD_FILES: dict[str, str] = {
    "world/meta.yaml": """\
id: world
unit: world
name: Shared world layer
description: The common landscape — technologies, markets, geopolitics. Names no tenant.
""",
    "world/components/cloud-compute.yaml": """\
id: cloud-compute
name: Cloud compute
kind: activity
evolution: commodity
visibility: 0.15
""",
    "world/components/content-delivery-network.yaml": """\
id: content-delivery-network
name: Content delivery network
kind: activity
evolution: product
visibility: 0.35
""",
    "world/components/euv-lithography.yaml": """\
id: euv-lithography
name: EUV lithography tooling
kind: activity
evolution: custom-built
visibility: 0.2
""",
    "world/components/leading-edge-process-node.yaml": """\
id: leading-edge-process-node
name: Leading-edge process node
kind: activity
evolution: product
visibility: 0.45
""",
    "world/propositions/dvd-rental-revenue-falls-faster-than-streaming-adds.yaml": """\
id: dvd-rental-revenue-falls-faster-than-streaming-adds
text: >-
  Physical rental revenue declines faster than streaming subscription revenue replaces it,
  over the stated horizon.
""",
    "world/propositions/euv-tool-deliveries-slip-past-2026.yaml": """\
id: euv-tool-deliveries-slip-past-2026
text: >-
  High-NA EUV tool deliveries required for the next process node slip beyond 2026.
""",
    "world/world_models/twin-default.yaml": """\
id: twin-default
name: The twin's own map
credence: 0.5
note: >-
  The default reference, holding no privileged status. It carries its own credence, sits
  alongside rival forecasts, and is falsified by revealed truth like any other model.
beliefs:
  dvd-rental-revenue-falls-faster-than-streaming-adds: 0.62
  euv-tool-deliveries-slip-past-2026: 0.55
""",
    "world/world_models/rival-fast-commoditisation.yaml": """\
id: rival-fast-commoditisation
name: Rival forecast — fast commoditisation
credence: 0.3
note: A plausible trajectory held simultaneously with the default. The spread is information.
beliefs:
  dvd-rental-revenue-falls-faster-than-streaming-adds: 0.81
  euv-tool-deliveries-slip-past-2026: 0.7
""",
}

OVERLAY_FILES: dict[str, str] = {
    "orgs/netflix/components/streaming-experience.yaml": """\
id: streaming-experience
name: Streaming experience
kind: activity
evolution: product
visibility: 0.9
needs:
  - content-delivery-network
  - cloud-compute
""",
    "orgs/netflix/components/dvd-by-mail.yaml": """\
id: dvd-by-mail
name: DVD by mail
kind: activity
evolution: commodity
visibility: 0.85
needs:
  - content-delivery-network
""",
    # Downstream of everything and evidenced by nothing. It exists so the use-gate has a real
    # subject: the only causal path here runs through a grade-5 model assertion.
    "orgs/netflix/components/brand-goodwill.yaml": """\
id: brand-goodwill
name: Brand goodwill
kind: capability
evolution: genesis
visibility: 0.6
""",
    "orgs/netflix/world_models/netflix-believed.yaml": """\
id: netflix-believed
name: The org's believed map
credence: 0.2
note: >-
  Where the org thinks things sit. The delta between believed and revealed is the
  anticipation failure, which is the thing worth measuring.
beliefs:
  dvd-rental-revenue-falls-faster-than-streaming-adds: 0.25
""",
    "orgs/netflix/signals/price-separation-announced.yaml": """\
id: price-separation-announced
date: '2011-07-12'
steep: economic
source: Public pricing announcement
statement: Streaming and physical rental are separated into two priced plans.
provenance:
  observed_by: fixture
  url: https://example.invalid/fixture/price-separation
""",
    "orgs/netflix/claims/bind-price-separation-to-dvd-by-mail.yaml": """\
id: bind-price-separation-to-dvd-by-mail
kind: binding
signal: price-separation-announced
component: dvd-by-mail
evidence_grade: 5
claimed_by: fixture-author (human)
evidence: Reading of the announcement; no corroborating instrumentation.
confidence: 0.6
""",
    "orgs/netflix/scenarios/dvd-decline-2011.yaml": """\
id: dvd-decline-2011
question: Does physical rental fall away faster than streaming replaces it?
proposition: dvd-rental-revenue-falls-faster-than-streaming-adds
at: '2011-07-12'
horizon: '2012-12-31'
components:
  - dvd-by-mail
  - streaming-experience
  - brand-goodwill
world_models:
  - twin-default
  - rival-fast-commoditisation
  - netflix-believed
""",
    "orgs/netflix/outcomes/dvd-decline-2011-resolved.yaml": """\
id: dvd-decline-2011-resolved
proposition: dvd-rental-revenue-falls-faster-than-streaming-adds
observed: true
resolved_on: '2012-12-31'
source: Fixture answer key (stands in for the segmental filing).
contamination: low
source_dated: true
note: >-
  The answer-key format (build ticket 08). `contamination` is what the memorisation discount
  is computed from at build ticket 40; `source_dated` records whether the source carries a date
  that can be checked against the execution time.
""",
    "orgs/intel/components/foundry-services.yaml": """\
id: foundry-services
name: Foundry services
kind: activity
evolution: custom-built
visibility: 0.7
needs:
  - leading-edge-process-node
  - euv-lithography
""",
    "orgs/intel/world_models/intel-believed.yaml": """\
id: intel-believed
name: The org's believed map
credence: 0.2
beliefs:
  euv-tool-deliveries-slip-past-2026: 0.35
""",
    "orgs/intel/signals/foundry-segment-loss-disclosed.yaml": f"""\
id: foundry-segment-loss-disclosed
date: '2024-08-01'
steep: economic
source: Segment disclosure
statement: The foundry segment is disclosed as loss-making at scale.
substrate: {ABSENT_SUBSTRATE}
provenance:
  observed_by: fixture
  url: https://example.invalid/fixture/foundry-segment
""",
    "orgs/intel/claims/bind-foundry-loss-to-foundry-services.yaml": """\
id: bind-foundry-loss-to-foundry-services
kind: binding
signal: foundry-segment-loss-disclosed
component: foundry-services
evidence_grade: 5
claimed_by: fixture-author (human)
evidence: Reading of the disclosure.
confidence: 0.7
""",
    "orgs/netflix/people/alex-rivera.yaml": """\
id: alex-rivera
role: Platform engineer
""",
    "orgs/netflix/people/sam-okafor.yaml": """\
id: sam-okafor
role: Logistics lead
""",
    "orgs/netflix/edges/alex-maintains-streaming-experience.yaml": """\
id: alex-maintains-streaming-experience
type: maintains
from: alex-rivera
to: streaming-experience
""",
    "orgs/netflix/edges/sam-owns-dvd-by-mail.yaml": """\
id: sam-owns-dvd-by-mail
type: owns
from: sam-okafor
to: dvd-by-mail
""",
    "orgs/netflix/edges/alex-knows-cloud-compute.yaml": """\
id: alex-knows-cloud-compute
type: knows
from: alex-rivera
to: cloud-compute
note: A structural fact about who could rebuild it, and nothing about how they are doing.
""",
    # The graded-edge fixture (build ticket 17): the boundary contract the £ track and the
    # skills track test against. Generated, never committed, so it cannot fossilise — a
    # downstream track reads it out of the emitted graph artefact.
    "orgs/netflix/edges/streaming-displaces-dvd.yaml": """\
id: streaming-displaces-dvd
type: influences
from: streaming-experience
to: dvd-by-mail
sign: negative
lag_days: 180
elasticity:
  min: 0.2
  mode: 0.45
  max: 0.8
evidence_grade: 3
confidence: 0.5
note: >-
  A calibrated range, not a point. The width is the honest part: nobody knows this number to
  two decimal places and a triple says so where a single figure would not.
""",
    "orgs/intel/edges/euv-delay-slips-the-node.yaml": """\
id: euv-delay-slips-the-node
type: influences
from: euv-lithography
to: leading-edge-process-node
sign: negative
lag_days: 365
elasticity:
  min: 0.5
  mode: 0.5
  max: 0.5
evidence_grade: 2
confidence: 0.4
note: >-
  A degenerate triple, on purpose. It is permitted and it is flagged, so false precision is
  visible in the artefact rather than hidden behind a range that has no width.
""",
    # The two ends of the use-gate, in one graph (build ticket 19). One edge is evidenced well
    # enough to carry a price; the other is a model assertion and never will be, however wide its
    # range says it is. Both are representable, and they must not look equally confident.
    "orgs/netflix/edges/cdn-capacity-lifts-streaming.yaml": """\
id: cdn-capacity-lifts-streaming
type: influences
from: content-delivery-network
to: streaming-experience
sign: positive
lag_days: 60
elasticity:
  min: 0.1
  mode: 0.25
  max: 0.4
evidence_grade: 2
confidence: 0.55
note: >-
  Repeated historical co-movement across more than one delivery build-out. Inside the published
  threshold, so a path made only of edges like this one may carry a price.
""",
    "orgs/netflix/edges/price-separation-erodes-goodwill.yaml": """\
id: price-separation-erodes-goodwill
type: influences
from: dvd-by-mail
to: brand-goodwill
sign: negative
lag_days: 30
elasticity:
  min: 0.05
  mode: 0.3
  max: 0.9
evidence_grade: 5
confidence: 0.2
note: >-
  A model assertion. Nothing observed it, nothing published it, nobody calibrated it. The width
  of the range is the honest part and it still never prices — this is exactly where parametric
  contamination hides.
""",
    # A regrade in each direction, so both are exercised. Strengthening is the one to be
    # suspicious of: it is how a model assertion becomes a measurement.
    "orgs/netflix/regrades/streaming-displaces-dvd-strengthened.yaml": """\
id: streaming-displaces-dvd-strengthened
subject: streaming-displaces-dvd
from_grade: 4
to_grade: 3
regraded_on: '2026-02-01'
by_role: model-steward
reason: >-
  A published account of the same displacement mechanism was found, so the claim moved off
  calibrated judgement and onto domain theory.
evidence: The reference is recorded against the edge; the mechanism is still not observed here.
note: >-
  Strengthened — to a lower number, which is the direction worth looking at twice.
""",
    "orgs/intel/regrades/euv-delay-slips-the-node-weakened.yaml": """\
id: euv-delay-slips-the-node-weakened
subject: euv-delay-slips-the-node
from_grade: 1
to_grade: 2
regraded_on: '2026-03-15'
by_role: model-steward
reason: >-
  The series behind the original grade covers repeated co-movement rather than a dated change
  with observable data on both sides of it.
evidence: Review of the source series against the ladder's grade-1 admission criterion.
""",
    # Two perspectives over the same overlay (build ticket 26). Nothing here ranks them and
    # nothing defaults to the first: `twin exposure` with no `--perspective` reports both.
    "orgs/netflix/perspectives/the-operator.yaml": """\
id: the-operator
name: The operator paying to run this twin
party: employer
pays: >-
  The organisation running the twin. The figures below are theirs and are stated as theirs
  rather than dressed as neutral.
cash_flow:
  - streaming-experience
  - dvd-by-mail
values:
  streaming-experience:
    amount: 120000000
    evidence_grade: 2
    basis: >-
      Subscription revenue attributable to the experience, from repeated segment reporting.
  dvd-by-mail:
    amount: 40000000
    evidence_grade: 2
    basis: Rental revenue on the dated separation, measured on both sides of it.
  brand-goodwill:
    evidence_grade: 5
    basis: >-
      A model assertion about reputational worth, with no path to a cash flow anybody measured.
      It carries no amount, because at this grade the schema refuses one — the register entry is
      the honest form and "reputation damage = the number below" is the rejected one.
ruin:
  insolvency: >-
    Any option carrying a real chance that the organisation cannot meet its obligations.
forbidden:
  no-response-that-depends-on-secrecy: >-
    Any response whose effect depends on the people it affects not knowing it is in place.
""",
    "orgs/netflix/perspectives/the-staff-council.yaml": """\
id: the-staff-council
name: The staff council's own perspective
party: employee-body
pays: >-
  The staff council, from its own funds. It shares the world layer, holds its own valuation, and
  needed no privilege from anybody to instantiate this.
cash_flow:
  - streaming-experience
  - dvd-by-mail
values:
  streaming-experience:
    amount: 3000000
    evidence_grade: 2
    basis: Members employed on the experience, at published pay scales.
  dvd-by-mail:
    amount: 9000000
    evidence_grade: 2
    basis: Members employed in physical distribution, at published pay scales.
  brand-goodwill:
    evidence_grade: 4
    basis: >-
      A calibrated judgement about how a reputational move reaches members. Recorded as judgement
      and outside the threshold, so it is a register entry and carries no figure.
ruin:
  loss-of-livelihood: >-
    Any option carrying a real chance that a member cannot meet their own obligations.
forbidden:
  no-compulsory-severance: Any response that requires compulsory severance.
note: >-
  The same scenario prices differently here, and the difference is the point. The employer's
  valuation is not the neutral one; it is one of these two.
""",
    # Candidate responses (build ticket 28). Two of the three cross a red line, and both are
    # priced at almost nothing on purpose: the pre-filter never looks at a cost, so the cheapness
    # is what makes "no magnitude brings it back" visible rather than merely asserted.
    "orgs/netflix/responses/expand-the-delivery-network.yaml": """\
id: expand-the-delivery-network
name: Expand the delivery network
addresses: content-delivery-network
cost:
  min: 20000000
  mode: 45000000
  max: 90000000
note: >-
  Crosses nothing. It survives the pre-filter and is costed as a range, never as a point.
""",
    "orgs/netflix/responses/instrument-viewers-without-telling-them.yaml": """\
id: instrument-viewers-without-telling-them
name: Instrument viewers without telling them
addresses: streaming-experience
cost:
  min: 1
  mode: 1
  max: 1
crosses:
  no-covert-sensing: >-
    The whole effect depends on the subjects not knowing the sensor is there.
note: >-
  Removed by the universal floor, in every twin, at any price. Costed at one unit in the model so
  that the pre-filter's indifference to magnitude is demonstrable rather than claimed.
""",
    "orgs/netflix/responses/stake-the-quarter-on-one-title.yaml": """\
id: stake-the-quarter-on-one-title
name: Stake the quarter on one title
addresses: streaming-experience
cost:
  min: 5
  mode: 5
  max: 5
crosses:
  insolvency: >-
    A real chance the organisation cannot meet its obligations if the title does not land.
note: >-
  Ruin-class for the operator and not for the staff council, which declares a different boundary.
  The same option is therefore removed under one eye and survives under the other, which is what
  perspective-relative ruin means when it is mechanical rather than rhetorical.
""",
    "orgs/intel/scenarios/euv-slip-2026.yaml": """\
id: euv-slip-2026
question: Does the tooling required for the next node arrive late enough to matter?
proposition: euv-tool-deliveries-slip-past-2026
at: '2024-08-01'
horizon: '2026-12-31'
components:
  - foundry-services
  - leading-edge-process-node
world_models:
  - twin-default
  - rival-fast-commoditisation
  - intel-believed
""",
}


def git(cwd: Path, *args: str) -> str:
    proc = subprocess.run(
        ["git", *_CONFIG, *args],
        cwd=str(cwd),
        env=dict(_GIT_ENV),
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    if proc.returncode != 0:
        raise RuntimeError(f"git {' '.join(args)}: {proc.stderr.decode('utf-8', 'replace').strip()}")
    return proc.stdout.decode("utf-8")


def _write(root: Path, files: dict[str, str]) -> None:
    for rel, content in files.items():
        path = root / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")


def build(dest: str | Path) -> Path:
    """Create the fixture repository at `dest` and return its path.

    Two commits on purpose: the world layer lands first so the overlays can pin the world
    commit they resolve against, which is what makes them separately versioned units.
    """
    root = Path(dest)
    root.mkdir(parents=True, exist_ok=True)
    git(root, "init", "-q", "-b", "main", "--object-format=sha1")

    _write(root, WORLD_FILES)
    git(root, "add", "-A")
    git(root, "commit", "-q", "-m", "world layer")
    world_commit = git(root, "rev-parse", "HEAD").strip()

    _write(root, OVERLAY_FILES)
    _write(root, BEHAVIOURAL_FILES)
    for org in ("netflix", "intel"):
        _write(
            root,
            {
                f"orgs/{org}/meta.yaml": (
                    f"id: {org}\nunit: overlay\norg: {org}\nworld_ref: {world_commit}\n"
                )
            },
        )
    git(root, "add", "-A")
    git(root, "commit", "-q", "-m", "org overlays")
    return root


BEHAVIOURAL_FILES: dict[str, str] = {
    "orgs/netflix/behavioural/meta.yaml": """\
id: netflix-behavioural
unit: behavioural
org: netflix
dpia: DPIA-2026-001
lawful_basis: Legitimate interests; balancing test recorded in DPIA-2026-001.
retention_days: 90
advisory_only: true
note: >-
  Cohort-level only. There is no person field in an observation and no slot for special-category
  data anywhere in the schema, so minimisation is structural rather than a policy to remember.
""",
    "orgs/netflix/behavioural/observations/deploy-friction-2011-q2.yaml": """\
id: deploy-friction-2011-q2
cohort: platform-engineering
metric: deploy-lead-time-index
value: 0.62
observed_on: '2011-06-30'
sensor: CI timings, aggregated weekly across the cohort.
gameability: medium
""",
}


def detach_behavioural(root: str | Path) -> str:
    """Delete the behavioural overlay. Everything else must still load — that is the point of it
    being a separate unit rather than a flag."""
    path = Path(root)
    git(path, "rm", "-r", "-q", "orgs/netflix/behavioural")
    git(path, "commit", "-q", "-m", "detach the behavioural overlay")
    return git(path, "rev-parse", "HEAD").strip()


def advance_world(root: str | Path) -> str:
    """Move the world layer on. Overlays pinned to the earlier commit must not shift."""
    path = Path(root)
    _write(
        path,
        {
            "world/components/high-na-euv.yaml": (
                "id: high-na-euv\nname: High-NA EUV\nkind: activity\n"
                "evolution: genesis\nvisibility: 0.1\n"
            )
        },
    )
    git(path, "add", "-A")
    git(path, "commit", "-q", "-m", "world moves on")
    return git(path, "rev-parse", "HEAD").strip()


# -- the pocket org (build ticket 15) ------------------------------------------------------
#
# Five components, six edges, named elasticities, and every number chosen so a reviewer can do
# the arithmetic in their head. It exists to catch the class of failure a refusal test cannot:
# a PERT triple that is present but garbage, an elasticity that stops being recalibrated three
# tickets later, a propagation that changed and nobody noticed. Those all stay green under a
# refusal test and all fail here, against `twin/pocket-org-worksheet.md`.
#
# It also decouples two tracks. The £ chain takes a distribution as input and does not care
# whether it came from Monte-Carlo propagation or from this fixture, so pricing can run parallel
# to propagation instead of behind it.

POCKET_WORLD: dict[str, str] = {
    # Names no tenant, in any file, in any field or any prose — `world_never_references_overlay`
    # holds for this fixture exactly as it does for the flagship one.
    "world/meta.yaml": """\
id: world
unit: world
name: Shared world layer
description: Deliberately thin. The subject is the overlay; the world layer holds no components.
""",
    "world/propositions/the-portal-misses-its-availability-target.yaml": """\
id: the-portal-misses-its-availability-target
text: The customer portal misses its stated availability target over the horizon.
""",
    "world/world_models/reference-map.yaml": """\
id: reference-map
name: The reference map
credence: 0.5
beliefs:
  the-portal-misses-its-availability-target: 0.4
""",
}

POCKET_OVERLAY: dict[str, str] = {
    "orgs/pocket/components/customer-portal.yaml": """\
id: customer-portal
name: Customer portal
kind: activity
evolution: product
evolution_position: 0.6
visibility: 0.9
needs:
  - order-service
""",
    "orgs/pocket/components/order-service.yaml": """\
id: order-service
name: Order service
kind: activity
evolution: product
evolution_position: 0.5
visibility: 0.7
needs:
  - payment-gateway
  - identity-store
""",
    "orgs/pocket/components/payment-gateway.yaml": """\
id: payment-gateway
name: Payment gateway
kind: activity
evolution: commodity
evolution_position: 0.8
visibility: 0.5
""",
    "orgs/pocket/components/identity-store.yaml": """\
id: identity-store
name: Identity store
kind: data
evolution: custom-built
evolution_position: 0.4
visibility: 0.3
needs:
  - shared-database
""",
    "orgs/pocket/components/shared-database.yaml": """\
id: shared-database
name: Shared database
kind: data
evolution: commodity
evolution_position: 0.9
visibility: 0.1
""",
    "orgs/pocket/edges/database-slows-orders.yaml": """\
id: database-slows-orders
type: influences
from: shared-database
to: order-service
sign: negative
lag_days: 7
elasticity:
  min: 0.3
  mode: 0.5
  max: 0.7
evidence_grade: 3
confidence: 0.6
""",
    "orgs/pocket/edges/orders-slow-the-portal.yaml": """\
id: orders-slow-the-portal
type: influences
from: order-service
to: customer-portal
sign: negative
lag_days: 14
elasticity:
  min: 0.4
  mode: 0.4
  max: 0.4
evidence_grade: 2
confidence: 0.5
note: >-
  Degenerate on purpose, so the worksheet carries one flagged edge and one honest range.
""",
    # `identity-store` is in the scenario so the £ boundary has a refused impact to demonstrate.
    # The operator values it well enough to carry a figure and no causal path runs from it to the
    # operator's cash flow, so it passes the use-gate and fails admission. Two different questions,
    # and the worksheet checks both answers (build ticket 29).
    "orgs/pocket/scenarios/portal-availability-2026.yaml": """\
id: portal-availability-2026
question: Does the customer portal miss its availability target over the horizon?
proposition: the-portal-misses-its-availability-target
at: '2026-01-01'
horizon: '2026-12-31'
components:
  - customer-portal
  - order-service
  - identity-store
world_models:
  - reference-map
""",
    # Two perspectives, hand-computable on purpose: 400000 + 250000 = 650000 against
    # 50000 + 120000 = 170000, so the spread is 480000 and every figure is checkable by eye.
    "orgs/pocket/perspectives/the-operator.yaml": """\
id: the-operator
name: The operator paying to run this twin
party: employer
pays: The organisation running the twin.
cash_flow:
  - customer-portal
values:
  customer-portal:
    amount: 400000
    evidence_grade: 2
    basis: Order value lost per hour of portal outage, from repeated incident records.
  order-service:
    amount: 250000
    evidence_grade: 1
    basis: The dated outage of 2025, with order volume measured on both sides of it.
  identity-store:
    amount: 90000
    evidence_grade: 2
    basis: >-
      Support hours on identity incidents, from repeated records. Well enough evidenced to carry
      a figure, and no causal edge leaves this component, so nothing reaches the operator's cash
      flow and the figure stays outside the currency.
ruin:
  insolvency: Any option carrying a real chance that the organisation cannot meet its obligations.
""",
    "orgs/pocket/perspectives/the-staff-council.yaml": """\
id: the-staff-council
name: The staff council's own perspective
party: employee-body
pays: The staff council, from its own funds.
cash_flow:
  - customer-portal
  - order-service
values:
  customer-portal:
    amount: 50000
    evidence_grade: 2
    basis: Members on portal support, at published pay scales.
  order-service:
    amount: 120000
    evidence_grade: 1
    basis: The dated outage of 2025, with overtime recorded on both sides of it.
ruin:
  loss-of-livelihood: >-
    Any option carrying a real chance that a member cannot meet their own obligations.
""",
    # Three candidate responses, and the two that cross a red line are priced at almost nothing on
    # purpose (build ticket 28). The pre-filter never reads a cost, so cheapness is what makes
    # "no magnitude brings an excluded option back" demonstrable rather than asserted.
    "orgs/pocket/responses/add-a-read-replica.yaml": """\
id: add-a-read-replica
name: Add a read replica
addresses: shared-database
cost:
  min: 10000
  mode: 25000
  max: 70000
note: >-
  Crosses nothing, so it survives the pre-filter and is costed. Its mean is 30000 by hand:
  (10000 + 4 x 25000 + 70000) / 6.
""",
    "orgs/pocket/responses/watch-the-team-quietly.yaml": """\
id: watch-the-team-quietly
name: Watch the team quietly
addresses: order-service
cost:
  min: 5000
  mode: 5000
  max: 5000
crosses:
  no-covert-sensing: >-
    The effect depends entirely on the people it measures not knowing it is running.
""",
    "orgs/pocket/responses/bet-the-org-on-one-supplier.yaml": """\
id: bet-the-org-on-one-supplier
name: Bet the org on one supplier
addresses: shared-database
cost:
  min: 1000
  mode: 1000
  max: 1000
crosses:
  insolvency: >-
    A real chance the organisation cannot meet its obligations if the supplier fails.
""",
}


def build_pocket_org(dest: str | Path) -> Path:
    """The pocket-org model repository. Same deterministic recipe as `build`."""
    root = Path(dest)
    root.mkdir(parents=True, exist_ok=True)
    git(root, "init", "-q", "-b", "main", "--object-format=sha1")

    _write(root, POCKET_WORLD)
    git(root, "add", "-A")
    git(root, "commit", "-q", "-m", "world layer")
    world_commit = git(root, "rev-parse", "HEAD").strip()

    _write(root, POCKET_OVERLAY)
    _write(root, {"orgs/pocket/meta.yaml": f"id: pocket\nunit: overlay\norg: pocket\nworld_ref: {world_commit}\n"})
    git(root, "add", "-A")
    git(root, "commit", "-q", "-m", "the pocket org")
    return root


def plant_unrecorded_regrade(root: str | Path, grade: int = 1) -> str:
    """Move an evidence grade in a commit and record nothing. The history check must bite.

    The chain check cannot see this: after the edit the edge simply declares a different grade
    and there is no chain to be inconsistent with. Only the file's own history says a grade moved
    (build ticket 18).
    """
    path = Path(root)
    rel = "orgs/netflix/edges/cdn-capacity-lifts-streaming.yaml"
    text = (path / rel).read_text(encoding="utf-8")
    (path / rel).write_text(
        text.replace("evidence_grade: 2", f"evidence_grade: {grade}"), encoding="utf-8", newline="\n"
    )
    git(path, "add", "-A")
    git(path, "commit", "-q", "-m", "quietly promote an edge to a stronger grade")
    return git(path, "rev-parse", "HEAD").strip()


def record_a_regrade(root: str | Path, grade: int = 4) -> str:
    """Move an evidence grade **and** write the regrade event, in one commit.

    The counterpart to `plant_unrecorded_regrade`: without it the history check would be vacuous
    here, because every fixture regrade records a move that predates the repository and there is
    no observed change for the check to match against.
    """
    path = Path(root)
    rel = "orgs/netflix/edges/cdn-capacity-lifts-streaming.yaml"
    text = (path / rel).read_text(encoding="utf-8")
    (path / rel).write_text(
        text.replace("evidence_grade: 2", f"evidence_grade: {grade}"), encoding="utf-8", newline="\n"
    )
    _write(
        path,
        {
            "orgs/netflix/regrades/cdn-capacity-weakened.yaml": f"""\
id: cdn-capacity-weakened
subject: cdn-capacity-lifts-streaming
from_grade: 2
to_grade: {grade}
regraded_on: '2026-06-01'
by_role: model-steward
reason: >-
  Review found the co-movement rested on one build-out rather than several, so the claim now
  rests on judgement.
evidence: Review of the underlying series.
"""
        },
    )
    git(path, "add", "-A")
    git(path, "commit", "-q", "-m", "regrade an edge, and record the regrade")
    return git(path, "rev-parse", "HEAD").strip()


def plant_world_violation(root: str | Path) -> str:
    """Commit a world-layer file that references an overlay. The guard must bite."""
    path = Path(root)
    _write(
        path,
        {
            "world/components/tenant-leak.yaml": (
                "id: tenant-leak\nname: Leaky world component\nkind: activity\n"
                "evolution: product\nvisibility: 0.5\nnotes:\n  - netflix\n"
            )
        },
    )
    git(path, "add", "-A")
    git(path, "commit", "-q", "-m", "plant a directional violation")
    return git(path, "rev-parse", "HEAD").strip()
