"""A deterministic fixture model repository.

Built rather than committed: boundary fixtures generated by code in CI never fossilise
(constitution, "the boundary fixtures"). Author, committer and dates are fixed, so the same
content produces the same commit sha on every machine — which is what makes a committed golden
digest, and therefore the cross-architecture determinism check, mean anything at all.

Two co-flagships: Netflix retrospective (a resolved outcome to score against) and Intel live
(a forecast with no answer key yet). Both at toy depth — this is a fixture, not a model.
"""

from __future__ import annotations

import os
import subprocess
from pathlib import Path

# Empty-blob digest: a substrate reference that deliberately resolves to nothing, so the
# reference form is exercised with no substrate present.
ABSENT_SUBSTRATE = "sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855:0"

_FIXED_DATE = "2026-01-01T00:00:00+00:00"
_GIT_ENV = {
    "GIT_AUTHOR_NAME": "twin fixture",
    "GIT_AUTHOR_EMAIL": "fixture@twin.invalid",
    "GIT_COMMITTER_NAME": "twin fixture",
    "GIT_COMMITTER_EMAIL": "fixture@twin.invalid",
    "GIT_AUTHOR_DATE": _FIXED_DATE,
    "GIT_COMMITTER_DATE": _FIXED_DATE,
    "GIT_CONFIG_NOSYSTEM": "1",
    "HOME": "/nonexistent-twin-fixture-home",
    "XDG_CONFIG_HOME": "/nonexistent-twin-fixture-home",
    "LC_ALL": "C",
    "TZ": "UTC",
    "PATH": os.environ.get("PATH", "/usr/bin:/bin"),
}
# Anything that could change the bytes git writes or the commit header it builds.
_CONFIG = [
    "-c", "core.autocrlf=false",
    "-c", "core.symlinks=false",
    "-c", "commit.gpgsign=false",
    "-c", "tag.gpgsign=false",
    "-c", "user.name=twin fixture",
    "-c", "user.email=fixture@twin.invalid",
]

WORLD_FILES: dict[str, str] = {
    "world/meta.yaml": """\
id: world
unit: world
name: Shared world layer
description: The common landscape — technologies, markets, geopolitics. Names no tenant.
""",
    "world/components/cloud-compute.yaml": """\
id: cloud-compute
name: Cloud compute
kind: activity
evolution: commodity
visibility: 0.15
""",
    "world/components/content-delivery-network.yaml": """\
id: content-delivery-network
name: Content delivery network
kind: activity
evolution: product
visibility: 0.35
""",
    "world/components/euv-lithography.yaml": """\
id: euv-lithography
name: EUV lithography tooling
kind: activity
evolution: custom-built
visibility: 0.2
""",
    "world/components/leading-edge-process-node.yaml": """\
id: leading-edge-process-node
name: Leading-edge process node
kind: activity
evolution: product
visibility: 0.45
""",
    "world/propositions/dvd-rental-revenue-falls-faster-than-streaming-adds.yaml": """\
id: dvd-rental-revenue-falls-faster-than-streaming-adds
text: >-
  Physical rental revenue declines faster than streaming subscription revenue replaces it,
  over the stated horizon.
""",
    "world/propositions/euv-tool-deliveries-slip-past-2026.yaml": """\
id: euv-tool-deliveries-slip-past-2026
text: >-
  High-NA EUV tool deliveries required for the next process node slip beyond 2026.
""",
    "world/world_models/twin-default.yaml": """\
id: twin-default
name: The twin's own map
credence: 0.5
note: >-
  The default reference, holding no privileged status. It carries its own credence, sits
  alongside rival forecasts, and is falsified by revealed truth like any other model.
beliefs:
  dvd-rental-revenue-falls-faster-than-streaming-adds: 0.62
  euv-tool-deliveries-slip-past-2026: 0.55
""",
    "world/world_models/rival-fast-commoditisation.yaml": """\
id: rival-fast-commoditisation
name: Rival forecast — fast commoditisation
credence: 0.3
note: A plausible trajectory held simultaneously with the default. The spread is information.
beliefs:
  dvd-rental-revenue-falls-faster-than-streaming-adds: 0.81
  euv-tool-deliveries-slip-past-2026: 0.7
""",
}

OVERLAY_FILES: dict[str, str] = {
    "orgs/netflix/components/streaming-experience.yaml": """\
id: streaming-experience
name: Streaming experience
kind: activity
evolution: product
visibility: 0.9
needs:
  - content-delivery-network
  - cloud-compute
""",
    "orgs/netflix/components/dvd-by-mail.yaml": """\
id: dvd-by-mail
name: DVD by mail
kind: activity
evolution: commodity
visibility: 0.85
needs:
  - content-delivery-network
""",
    "orgs/netflix/world_models/netflix-believed.yaml": """\
id: netflix-believed
name: The org's believed map
credence: 0.2
note: >-
  Where the org thinks things sit. The delta between believed and revealed is the
  anticipation failure, which is the thing worth measuring.
beliefs:
  dvd-rental-revenue-falls-faster-than-streaming-adds: 0.25
""",
    "orgs/netflix/signals/price-separation-announced.yaml": """\
id: price-separation-announced
date: '2011-07-12'
steep: economic
source: Public pricing announcement
statement: Streaming and physical rental are separated into two priced plans.
provenance:
  observed_by: fixture
  url: https://example.invalid/fixture/price-separation
""",
    "orgs/netflix/claims/bind-price-separation-to-dvd-by-mail.yaml": """\
id: bind-price-separation-to-dvd-by-mail
kind: binding
signal: price-separation-announced
component: dvd-by-mail
evidence_grade: 5
claimed_by: fixture-author (human)
evidence: Reading of the announcement; no corroborating instrumentation.
confidence: 0.6
""",
    "orgs/netflix/scenarios/dvd-decline-2011.yaml": """\
id: dvd-decline-2011
question: Does physical rental fall away faster than streaming replaces it?
proposition: dvd-rental-revenue-falls-faster-than-streaming-adds
at: '2011-07-12'
horizon: '2012-12-31'
components:
  - dvd-by-mail
  - streaming-experience
world_models:
  - twin-default
  - rival-fast-commoditisation
  - netflix-believed
""",
    "orgs/netflix/outcomes/dvd-decline-2011-resolved.yaml": """\
id: dvd-decline-2011-resolved
proposition: dvd-rental-revenue-falls-faster-than-streaming-adds
observed: true
resolved_on: '2012-12-31'
source: Fixture answer key (stands in for the segmental filing).
contamination: low
source_dated: true
note: >-
  The answer-key format (build ticket 08). `contamination` is what the memorisation discount
  is computed from at build ticket 40; `source_dated` records whether the source carries a date
  that can be checked against the execution time.
""",
    "orgs/intel/components/foundry-services.yaml": """\
id: foundry-services
name: Foundry services
kind: activity
evolution: custom-built
visibility: 0.7
needs:
  - leading-edge-process-node
  - euv-lithography
""",
    "orgs/intel/world_models/intel-believed.yaml": """\
id: intel-believed
name: The org's believed map
credence: 0.2
beliefs:
  euv-tool-deliveries-slip-past-2026: 0.35
""",
    "orgs/intel/signals/foundry-segment-loss-disclosed.yaml": f"""\
id: foundry-segment-loss-disclosed
date: '2024-08-01'
steep: economic
source: Segment disclosure
statement: The foundry segment is disclosed as loss-making at scale.
substrate: {ABSENT_SUBSTRATE}
provenance:
  observed_by: fixture
  url: https://example.invalid/fixture/foundry-segment
""",
    "orgs/intel/claims/bind-foundry-loss-to-foundry-services.yaml": """\
id: bind-foundry-loss-to-foundry-services
kind: binding
signal: foundry-segment-loss-disclosed
component: foundry-services
evidence_grade: 5
claimed_by: fixture-author (human)
evidence: Reading of the disclosure.
confidence: 0.7
""",
    "orgs/netflix/people/alex-rivera.yaml": """\
id: alex-rivera
role: Platform engineer
""",
    "orgs/netflix/people/sam-okafor.yaml": """\
id: sam-okafor
role: Logistics lead
""",
    "orgs/netflix/edges/alex-maintains-streaming-experience.yaml": """\
id: alex-maintains-streaming-experience
type: maintains
from: alex-rivera
to: streaming-experience
""",
    "orgs/netflix/edges/sam-owns-dvd-by-mail.yaml": """\
id: sam-owns-dvd-by-mail
type: owns
from: sam-okafor
to: dvd-by-mail
""",
    "orgs/netflix/edges/alex-knows-cloud-compute.yaml": """\
id: alex-knows-cloud-compute
type: knows
from: alex-rivera
to: cloud-compute
note: A structural fact about who could rebuild it, and nothing about how they are doing.
""",
    "orgs/intel/scenarios/euv-slip-2026.yaml": """\
id: euv-slip-2026
question: Does the tooling required for the next node arrive late enough to matter?
proposition: euv-tool-deliveries-slip-past-2026
at: '2024-08-01'
horizon: '2026-12-31'
components:
  - foundry-services
  - leading-edge-process-node
world_models:
  - twin-default
  - rival-fast-commoditisation
  - intel-believed
""",
}


def git(cwd: Path, *args: str) -> str:
    proc = subprocess.run(
        ["git", *_CONFIG, *args],
        cwd=str(cwd),
        env=dict(_GIT_ENV),
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    if proc.returncode != 0:
        raise RuntimeError(f"git {' '.join(args)}: {proc.stderr.decode('utf-8', 'replace').strip()}")
    return proc.stdout.decode("utf-8")


def _write(root: Path, files: dict[str, str]) -> None:
    for rel, content in files.items():
        path = root / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")


def build(dest: str | Path) -> Path:
    """Create the fixture repository at `dest` and return its path.

    Two commits on purpose: the world layer lands first so the overlays can pin the world
    commit they resolve against, which is what makes them separately versioned units.
    """
    root = Path(dest)
    root.mkdir(parents=True, exist_ok=True)
    git(root, "init", "-q", "-b", "main", "--object-format=sha1")

    _write(root, WORLD_FILES)
    git(root, "add", "-A")
    git(root, "commit", "-q", "-m", "world layer")
    world_commit = git(root, "rev-parse", "HEAD").strip()

    _write(root, OVERLAY_FILES)
    _write(root, BEHAVIOURAL_FILES)
    for org in ("netflix", "intel"):
        _write(
            root,
            {
                f"orgs/{org}/meta.yaml": (
                    f"id: {org}\nunit: overlay\norg: {org}\nworld_ref: {world_commit}\n"
                )
            },
        )
    git(root, "add", "-A")
    git(root, "commit", "-q", "-m", "org overlays")
    return root


BEHAVIOURAL_FILES: dict[str, str] = {
    "orgs/netflix/behavioural/meta.yaml": """\
id: netflix-behavioural
unit: behavioural
org: netflix
dpia: DPIA-2026-001
lawful_basis: Legitimate interests; balancing test recorded in DPIA-2026-001.
retention_days: 90
advisory_only: true
note: >-
  Cohort-level only. There is no person field in an observation and no slot for special-category
  data anywhere in the schema, so minimisation is structural rather than a policy to remember.
""",
    "orgs/netflix/behavioural/observations/deploy-friction-2011-q2.yaml": """\
id: deploy-friction-2011-q2
cohort: platform-engineering
metric: deploy-lead-time-index
value: 0.62
observed_on: '2011-06-30'
sensor: CI timings, aggregated weekly across the cohort.
gameability: medium
""",
}


def detach_behavioural(root: str | Path) -> str:
    """Delete the behavioural overlay. Everything else must still load — that is the point of it
    being a separate unit rather than a flag."""
    path = Path(root)
    git(path, "rm", "-r", "-q", "orgs/netflix/behavioural")
    git(path, "commit", "-q", "-m", "detach the behavioural overlay")
    return git(path, "rev-parse", "HEAD").strip()


def advance_world(root: str | Path) -> str:
    """Move the world layer on. Overlays pinned to the earlier commit must not shift."""
    path = Path(root)
    _write(
        path,
        {
            "world/components/high-na-euv.yaml": (
                "id: high-na-euv\nname: High-NA EUV\nkind: activity\n"
                "evolution: genesis\nvisibility: 0.1\n"
            )
        },
    )
    git(path, "add", "-A")
    git(path, "commit", "-q", "-m", "world moves on")
    return git(path, "rev-parse", "HEAD").strip()


def plant_world_violation(root: str | Path) -> str:
    """Commit a world-layer file that references an overlay. The guard must bite."""
    path = Path(root)
    _write(
        path,
        {
            "world/components/tenant-leak.yaml": (
                "id: tenant-leak\nname: Leaky world component\nkind: activity\n"
                "evolution: product\nvisibility: 0.5\nnotes:\n  - netflix\n"
            )
        },
    )
    git(path, "add", "-A")
    git(path, "commit", "-q", "-m", "plant a directional violation")
    return git(path, "rev-parse", "HEAD").strip()
