apiVersion: policies.kyverno.io/v1alpha1
kind: MutatingPolicy
metadata: {name: mut-min}
spec:
  matchConstraints:
    resourceRules:
    - apiGroups: ['']
      apiVersions: [v1]
      operations: [CREATE, UPDATE]
      resources: [pods]
  matchConditions:
  - name: is-caged
    expression: object.metadata.?labels['caged'].orValue('') == 'true'
  mutations:
  - patchType: ApplyConfiguration
    applyConfiguration:
      expression: 'Object{metadata: Object.metadata{labels: {"seen": "yes"}}}'
