"""The other hand: the second identity that reviews and merges (ticket 88, ticket 75 Q6/Q14).

A GitHub App authenticates in two steps: a short-lived JWT signed with the app's private key
proves "I am the app"; an installation token minted with that JWT acts on one installation's
repositories. Nothing here holds a credential: the key is a path, read at call time.

These tests use a throwaway RSA key generated by `openssl` in a temp dir. The HTTP half is
exercised against a fake opener so no network is touched.
"""

from __future__ import annotations

import base64
import json
import subprocess
from pathlib import Path

import pytest

from twin import other_hand


def _b64url_decode(part: str) -> bytes:
    return base64.urlsafe_b64decode(part + "=" * (-len(part) % 4))


@pytest.fixture
def rsa_key(tmp_path: Path) -> tuple[Path, Path]:
    priv = tmp_path / "app.pem"
    pub = tmp_path / "app.pub"
    subprocess.run(
        ["openssl", "genpkey", "-algorithm", "RSA", "-pkeyopt", "rsa_keygen_bits:2048", "-out", str(priv)],
        check=True, capture_output=True,
    )
    subprocess.run(["openssl", "rsa", "-in", str(priv), "-pubout", "-out", str(pub)], check=True, capture_output=True)
    return priv, pub


def test_app_jwt_is_rs256_with_the_app_as_issuer_and_a_short_life(rsa_key: tuple[Path, Path]) -> None:
    priv, _ = rsa_key
    token = other_hand.app_jwt("4819564", priv, now=1_800_000_000)
    header, payload, _sig = token.split(".")
    assert json.loads(_b64url_decode(header)) == {"alg": "RS256", "typ": "JWT"}
    claims = json.loads(_b64url_decode(payload))
    assert claims["iss"] == "4819564"
    assert claims["iat"] == 1_800_000_000 - 60, "iat is backdated a minute for clock skew"
    assert claims["exp"] == 1_800_000_000 + 540, "nine minutes, under GitHub's ten-minute cap"


def test_app_jwt_has_no_base64_padding(rsa_key: tuple[Path, Path]) -> None:
    priv, _ = rsa_key
    token = other_hand.app_jwt("1", priv, now=1_800_000_000)
    assert "=" not in token


def test_app_jwt_signature_verifies_with_the_public_key(rsa_key: tuple[Path, Path], tmp_path: Path) -> None:
    priv, pub = rsa_key
    token = other_hand.app_jwt("4819564", priv, now=1_800_000_000)
    header, payload, sig = token.split(".")
    signed = (tmp_path / "signed.txt")
    signed.write_bytes(f"{header}.{payload}".encode("ascii"))
    sigfile = tmp_path / "sig.bin"
    sigfile.write_bytes(_b64url_decode(sig))
    result = subprocess.run(
        ["openssl", "dgst", "-sha256", "-verify", str(pub), "-signature", str(sigfile), str(signed)],
        capture_output=True, text=True,
    )
    assert result.returncode == 0, result.stderr
    assert "Verified OK" in result.stdout


def test_app_jwt_refuses_a_missing_key(tmp_path: Path) -> None:
    with pytest.raises(other_hand.OtherHandError, match="private key"):
        other_hand.app_jwt("1", tmp_path / "absent.pem", now=1_800_000_000)


class _FakeOpener:
    """Records requests and answers them from a canned table keyed on (method, path)."""

    def __init__(self, answers: dict[tuple[str, str], object]) -> None:
        self.answers = answers
        self.calls: list[dict[str, object]] = []

    def __call__(self, method: str, path: str, bearer: str, body: dict[str, object] | None = None) -> object:
        self.calls.append({"method": method, "path": path, "bearer": bearer, "body": body})
        try:
            return self.answers[(method, path)]
        except KeyError as exc:  # pragma: no cover - a test wrote the wrong table
            raise AssertionError(f"unexpected call {method} {path}") from exc


def test_whoami_reads_the_app_slug_with_the_jwt() -> None:
    opener = _FakeOpener({("GET", "/app"): {"slug": "pavc-other-hand", "id": 4819564}})
    assert other_hand.whoami("jwt-1", opener=opener) == "pavc-other-hand"
    assert opener.calls == [{"method": "GET", "path": "/app", "bearer": "jwt-1", "body": None}]


def test_installation_for_org_finds_the_installation_by_account_login() -> None:
    opener = _FakeOpener({
        ("GET", "/app/installations"): [
            {"id": 11, "account": {"login": "policy-as-versioned-flux"}},
            {"id": 22, "account": {"login": "policy-as-versioned-driftwood"}},
        ],
    })
    assert other_hand.installation_for_org("jwt-1", "policy-as-versioned-driftwood", opener=opener) == 22


def test_installation_for_org_refuses_an_org_the_app_is_not_installed_on() -> None:
    opener = _FakeOpener({("GET", "/app/installations"): []})
    with pytest.raises(other_hand.OtherHandError, match="not installed"):
        other_hand.installation_for_org("jwt-1", "policy-as-versioned-nist", opener=opener)


def test_installation_token_posts_to_the_installation_and_returns_the_token() -> None:
    opener = _FakeOpener({
        ("POST", "/app/installations/22/access_tokens"): {"token": "ghs_fake", "expires_at": "2026-09-03T00:00:00Z"},
    })
    assert other_hand.installation_token("jwt-1", 22, opener=opener) == "ghs_fake"
    assert opener.calls[0]["method"] == "POST"
    assert opener.calls[0]["bearer"] == "jwt-1"


def test_settings_default_to_the_registered_app_and_the_config_dir(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.delenv("PAVC_OTHER_HAND_APP_ID", raising=False)
    monkeypatch.delenv("PAVC_OTHER_HAND_KEY", raising=False)
    settings = other_hand.settings()
    assert settings.app_id == "4819564"
    assert settings.key_path == Path.home() / ".config" / "pavc-other-hand" / "app.pem"


def test_settings_read_the_environment_first(monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> None:
    monkeypatch.setenv("PAVC_OTHER_HAND_APP_ID", "999")
    monkeypatch.setenv("PAVC_OTHER_HAND_KEY", str(tmp_path / "k.pem"))
    settings = other_hand.settings()
    assert settings.app_id == "999"
    assert settings.key_path == tmp_path / "k.pem"
