apiVersion: cli.kyverno.io/v1alpha1
kind: Test
metadata:
  name: mpol-skip
policies: [policy.yaml]
resources: [resources.yaml]
results:
- policy: mc-mut
  rule: mc-mut
  kind: Pod
  resources: [pod-in]
  patchedResources: patched.yaml
  result: pass
- policy: mc-mut
  rule: mc-mut
  kind: Pod
  resources: [pod-out]
  result: skip
